name: Unit Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 06 * * 1"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ["8.1", "8.2"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with pre-release PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - run: sudo apt-get update && sudo apt-get install -y faketime nmap

      - name: Run ncat command
        run: ncat --version

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Tests
        run: vendor/bin/phpunit
